[package]
name = "xcur"
version = "0.1.1"
authors = ["Jean Pierre Dudey <jeandudey@hotmail.com>"]
license = "GPL-3.0"
description = "Library for parsing XCursor files"

[dependencies]
nom = "1.2.4"

clippy = { version = "0.0.80", optional = true }

[features]
default = []
dev = ["clippy"]
